AConfig/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MFood.urls')),
    path('', include('MPhoto.urls')),
    path('', include('MCModel.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MCModel/urls.py
from django.urls import path
from .views import (
    main_view,
    get_json_car_data,
    get_json_model_data,
    create_order,
)

app_name = "orders"

urlpatterns = [
    path('cars', main_view, name='main-view'),
    path('cars-json/', get_json_car_data, name='cars-json'),
    path('models-json/<str:car>/', get_json_model_data, name='models-json'),
    path('create/', create_order, name='create-order'),
]

MFood/urls.py
from django.contrib import admin
from django.urls import path
from .views import dashboard_view, foodcreate_view,fooddelete_view, ordercreate_view, search_engine, foodupdate_view
urlpatterns = [
     path('', dashboard_view, name="dashboard"),
     
     #FOOD CRUD
     path('food/create', foodcreate_view, name="foodcreate"),
     path('food/delete', fooddelete_view, name="fooddelete"),
     path('food/update', foodupdate_view, name="foodupdate"),

     #ORDER CRUD 
     path('order/create', ordercreate_view, name="ordercreate"),
     
     path('search_results', search_engine, name="search_engine")

]

MFood/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return "{}".format(self.name)


class Food(models.Model):
    name = models.CharField(max_length=20, null= True)
    category = models.ForeignKey(Category, models.SET_NULL, null=True)
    price = models.PositiveIntegerField(null=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "{}".format(self.name)
    
    def get_absolute_url(self):
        return reverse("model_detail", kwargs={"pk": self.pk,"slug":self.name
                                               })

class OrderFood(models.Model):
    STATUS_FOOD=(
        ('Pending','pending'),
        ('Completed','completed')
    )    
    order = models.ForeignKey(Food, on_delete=models.CASCADE, null=True)     
    ordered_by = models.ForeignKey(User, on_delete= models.CASCADE, null = True)
    ordered_on = models.DateTimeField(auto_now_add=True)
    status =models.CharField(choices=STATUS_FOOD, max_length=15)
    
    def __str__(self):
        return "{} ordered by {}".format(self.order, self.ordered_by)    

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <title>Product Management System</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/semantic.js' %}" defer>

    </script>

    <script src="{% static 'js/photo2.js' %}" defer></script>
</head>

<body>

    <div class="container-fluid">
        <div class="row">

            <!-- Generic SideBar-->
            <div class="col-2  sidebar">
                <div class="d-flex flex-column flex-shrink-0 p-3">
                    <a href="/"
                        class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                        <h1><strong>Foodie</strong></h1>
                    </a>
                    <hr>

                    <ul class="nav-pills flex-column mb-auto">

                        <li>
                            <a href="{% url 'photo-list-view' %}" class="nav-link link-dark">
                                <i class="bi bi-grid"></i>
                                Ajax Live Listing
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'photo-view' %}" class="nav-link link-dark">
                                <i class="bi bi-grid"></i>
                                Photo Upload without page reload
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'photo-progress-view' %}" class="nav-link link-dark">
                                <i class="bi bi-grid"></i>
                                Photo Upload with Progress
                            </a>
                        </li>
                      
                        <li>
                            <a href="{% url 'orders:main-view' %}" class="nav-link link-dark">
                                <i class="bi bi-grid"></i>
                                Dependent DropDown
                            </a>
                        </li>

                    </ul>

                    <hr>
                    <div class="dropdown">
                        <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle"
                            id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://github.com/mdo.png" alt="" width="32" height="32"
                                class="rounded-circle me-2">
                            <strong>{{request.user.username}}</strong>
                        </a>
                        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Sign out</a></li>
                        </ul>
                    </div>

                </div>
            </div>

            <!--Container list-->
            <div class="col detailbar">

                {% block body %}

                {% endblock %}
            </div>

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

    {% include 'searchenginedata.html' %}
    {% include 'foodcruddata.html' %}
    {% include 'ordercruddata.html' %}
    {% block script %}

    {% endblock %}
</body>

</html>

templates/foodcruddata.html
<script>
    $(document).ready(function () {

        //CreateData
        $('#createfBtn').click(function () {
            output = " ";
            let sid = $('#getid').val()
            let foodname = $('#id_name').val()
            let category = $('#id_category').val()
            let price = $('#id_price').val()
            let added_by = $('#id_added_by').val()
            let added_on = $('#id_added_on').val()
            let updated_on = $('#id_updated_on').val()
            let csrfmiddlewaretoken = $(".foodform input[name='csrfmiddlewaretoken']").val()
            if (foodname == " " || category == " " || price == " " || added_by == " " || updated_on == " " || added_on == " ") {
                $('.messages').text("All Fields are mandatory!");
                $('.messages').show()

            } else if (category == " ") {
                console.log("sdfs");
            }
            else {
                //create a fdata dictionary
                fdata = {
                    'sid': sid,
                    'name': foodname,
                    'category': category,
                    'price': price,
                    'added_by': added_by,
                    'added_on': added_on,
                    'updated_on': updated_on,
                    'csrfmiddlewaretoken': csrfmiddlewaretoken
                },
                    console.log('Data:', fdata);

                console.log("Sending Data...")
                $.ajax({
                    url: "{% url 'foodcreate' %}",
                    method: "POST",
                    data: fdata,
                    dataType: 'json',
                    success: function (response) {

                        if (response.status == 'update') {
                            htmlp = "<div style='background-color: rgba(107, 255, 1, 0.92);text-align: center; padding:1rem; color: white;' role='alert'><strong>Food Updated Sucessfully!</strong></div>"
                            $('.messages').html(htmlp);
                            $('.messages').show()
                            x = response.food_queryset
                            console.log(x);
                            for (i = 0; i < x.length; i++) {

                                let added_on = new Date(x[i].added_on);

                                output += "<tr>" +
                                    "<td>" + x[i].name + "</td>" +
                                    "<td>" + "Rs " + x[i].price + " /- " + "</td>" +
                                    "<td>" + new Date(added_on | date) + "</td>" +
                                    "<td><input type='button'  id='updatefBtn' class='btn btn-info btn-sm' value='Update' data-foodkey =" + x[i].id + ">" +
                                    "<td><input type='button'  id='deletefBtn' class='btn btn-danger btn-sm' value='Delete' data-foodkey =" + x[i].id + ">" +
                                    "</tr>"
                            }
                            $('.food-list tbody').html(output)
                            $("#getid").val('');
                            $(".foodform")[0].reset();
                        }
                        if (response.status == 'create') {
                            htmlp = "<div style='background-color: rgba(107, 255, 1, 0.92);text-align: center; padding:1rem; color: white;' role='alert'><strong>Food Created Sucessfully!</strong></div>"
                            $('.messages').html(htmlp);
                            $('.messages').show()
                            x = response.food_queryset
                            console.log(x);
                            for (i = 0; i < x.length; i++) {
                                output += "<tr>" +
                                    "<td>" + x[i].name + "</td>" +
                                    "<td>" + "Rs " + x[i].price + " /- " + "</td>" +
                                    "<td>" + x[i].added_on + "</td>" +
                                    "<td><input type='button' id='updatefBtn' class='btn btn-info btn-sm' value='Update' data-foodkey =" + x[i].id + ">" +
                                    "<td><input type='button'  id='deletefBtn'  class='btn btn-danger btn-sm' value='Delete' data-foodkey =" + x[i].id + ">" +
                                    "</tr>"
                            }
                            $('.food-list tbody').html(output)
                            $("#getid").val('');
                            $(".foodform")[0].reset();
                        }
                        if (response.status == 'error') {
                            htmlp = "<div style='background-color:rgba(255, 7, 7, 0.92);text-align: center; padding:1rem; color: white;' role='alert'><strong>All fields are mandatory !</strong></div>"
                            $('.messages').html(htmlp);
                            $('.messages').show()
                        }
                    },
                    error: function (error) {
                        console.log(error)
                    }
                })

            }
        })

        //DeleteData
        $('tbody').on('click', '#deletefBtn', function () {
            output = " ";
            let key = $(this).attr('data-foodkey')
            let csrfmiddlewaretoken = $(".foodform input[name='csrfmiddlewaretoken']").val()
            fdata = {
                'id': key,
                'csrfmiddlewaretoken': csrfmiddlewaretoken
            },
                console.log('Data:', fdata);
            console.log("Sending Data...")
            $.ajax({
                url: "{% url 'fooddelete' %}",
                method: "POST",
                data: fdata,
                dataType: 'json',
                success: function (response) {
                    if (response.action == 'delete') {
                        htmlp = "<div style='background-color:rgba(255, 7, 7, 0.92);text-align: center; padding:1rem; color: white;' role='alert'><strong>Product deleted !</strong></div>"
                        $('.messages').html(htmlp);
                        $('.messages').show()
                        x = response.food_queryset
                        console.log(x);
                        for (i = 0; i < x.length; i++) {
                            output += "<tr>" +
                                "<td>" + x[i].name + "</td>" +
                                "<td>" + "Rs " + x[i].price + " /- " + "</td>" +
                                "<td>" + x[i].added_on + "</td>" +
                                "<td><input type='button' class='btn btn-info btn-sm' id='updatefBtn'  value='Update' data-foodkey=" + x[i].id + ">" +
                                "<td><input type='button' class='btn btn-danger btn-sm' id='deletefBtn'  value='Delete' data-foodkey=" + x[i].id + ">" +
                                "</tr>"
                        }
                        $('.food-list tbody').html(output)
                        $("form")[0].reset();
                    }

                },
                error: function (error) {
                    console.log(error)
                }
            })
        })


        //UpdateData
        $('tbody').on('click', '#updatefBtn', function () {
            output = " ";
            let key = $(this).attr('data-foodkey')
            let csrfmiddlewaretoken = $(".foodform input[name='csrfmiddlewaretoken']").val()
            fdata = {
                'id': key,
                'csrfmiddlewaretoken': csrfmiddlewaretoken
            },
                console.log('Data:', fdata);
            console.log("Sending Data...")
            $.ajax({
                url: "{% url 'foodupdate' %}",
                method: "POST",
                data: fdata,
                dataType: 'json',
                success: function (data) {
                    console.log(data)
                    $('.foodform h5 strong').text("Update Food");
                    $('.messages').show()

                    $('#createfBtn').text("Save");
                    $('.messages').show()
                    $("#getid").val(data.id);
                    $("#id_name").val(data.name);
                    $("#id_price").val(data.price);//put the values in the add/student field box.
                    $("#id_category").val(data.category.rname);
                    $("#id_added_by").val(data.added_by);
                    $("#id_added_on").val(data.added_on);
                    $("#id_updated_on").val(data.updated_on);

                },
                error: function (error) {
                    console.log(error)
                }
            })
        })

    })


</script>

templates/foodupdate.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
    
    <div class="col-4 mt- 5 ">

        <form class="form-container" action="#" autocomplete="on">
            <h5 class="text-center"><strong>Create Food</strong></h5><br>
            
            {% for field in foodform%}
                <label class="form-label">{{field.label}}</label>
                {{field}}
                <div class="invalid-feedback">
                    {{field.errors}}
                </div>
            {% endfor %}
    
            <input type="submit" class="btn btn-primary mt-2 btn-sm" value="Create">
    
        </form>

    </div>

</div>

{% endblock %}

templates/getfood.html
<script>
    $(document).ready(function(){
                setInterval(function(){
                    $.ajax({
                    url: "{% url 'food-list-view' %}",
                    method: 'GET',
                    success: function (response) {
                            console.log(response)
                            $('tbody').empty();
                            let output = ' ';
                            for(var i in response.foods){
                                
                                output += "<tr>" +
                                                "<td>" + response.foods[i].name + "</td>" +
                                                "<td>" + response.foods[i].price + "</td>" +
                                                "<td>" + response.foods[i].added_on + "</td>" +
                                                "<td><input type='button'  id='updatefBtn' class='btn btn-info btn-sm' value='Update' data-foodkey =" + response.foods[i].id + ">" +
                                                "<td><input type='button'  id='deletefBtn' class='btn btn-danger btn-sm' value='Delete' data-foodkey =" + response.foods[i].id + ">" +
                                                "</tr>"                         
                            }
                            $('tbody').html(output)
                    },
                    error: function (error) {
                        console.log(error)
                    }
                });
        },1000)
    
    })
    
    </script>

templates/main.html
{% extends 'base.html' %}
{% block body %}
<div class="row">

    <div class="col-12">
        <div class="container   text-center search-container">
            <h1>Search Engine</h1>

            <form method="get" class="w-50" id="search-form">
                {% csrf_token %}
                <div class="form-field">
                    <input type="text" class="p-3 search-input form-control" placeholder="Search Foods..."
                        id="search-input">
                </div>
                <div class="search-results not-visible" id="search-query">
                </div>
            </form>

        </div>
    </div>


    <br><br>
    <br><br>
    <div class="col-lg-4  col-md-12 mt- 5 ">

        <h5 class="text-center p-1 m-1"><strong class="messages "></strong></h5>


        <form class="form-container foodform" method="POST" autocomplete="on">
            <h5 class="text-center"><strong>Create Food</strong></h5>
            <hr>
            <input type="hidden" name="getid" id="getid" />
            <input type="hidden" name="id_updated_on" id="id_updated_on" />
            <input type="hidden" name="id_added_on" id="id_added_on" />
            {% csrf_token %}
            {% for field in foodform%}
            <label class="form-label">{{field.label}}</label>
            {{field}}
            <div class="invalid-feedback">
                {{field.errors}}
            </div>
            {% endfor %}

        </form>
        <button id="createfBtn" class="btn btn-primary ms-3 mt-2 btn-sm">Create</button>
    </div>

    <div class="col-lg-7 col-md-12 food-list">

        <div class="table-responsive">
            <h3 class="text-center"><strong>Food List</strong></h3><br>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">FoodName</th>
                        <th scope="col">Price</th>
                        <th scope="col">Added on</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>

                <tbody>
                    {% for i in food_queryset %}
                    <tr>
                        <td>{{i.name}}</td>
                        <td>Rs {{i.price}} /-</td>
                        <td>{{i.added_on}}</td>
                        <td><input type='button' class='btn btn-info btn-sm' value='Update' id="updatefBtn"
                                data-foodkey="{{i.id}}"></td>
                        <td><input type='button' class='btn btn-danger btn-sm' value='Delete' id="deletefBtn"
                                data-foodkey="{{i.id}}"></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>

<hr>
<div class="row">
    <div class="col-lg-4  col-md-12 mt- 5 ">

        <h5 class="text-center p-1 m-1"><strong class="order-messages "></strong></h5>


        <form class="order-container orderform" method="POST" autocomplete="on">
            <h5 class="text-center"><strong>Create Order</strong></h5>
            <hr>
            <input type="hidden" name="getid" id="getid" />
            <input type="hidden" name="id_updated_on" id="id_updated_on" />
            <input type="hidden" name="id_added_on" id="id_added_on" />
            {% csrf_token %}
            {% for field in orderform%}
            <label class="form-label">{{field.label}}</label>
            {{field}}
            <div class="invalid-feedback">
                {{field.errors}}
            </div>
            {% endfor %}

        </form>
        <button id="createoBtn" class="btn btn-primary ms-3 mt-2 btn-sm">Create</button>
    </div>

    <!--OrderList-->
    <div class="col-lg-8 col-md-12 order-list">

        <div class="table-responsive">
            <h3 class="text-center"><strong>Order List</strong></h3><br>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Order</th>
                        <th scope="col">Ordered_by</th>
                        <th scope="col">Ordered_on</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>

                <tbody>
                    {% for i in orderfood_queryset %}
                    <tr>
                        <td>{{i.order}}</td>
                        <td>{{i.ordered_by}}</td>
                        <td>{{i.ordered_on}}</td>
                        <td>{{i.status}}</td>
                        <td><input type='button' class='btn btn-info btn-sm' value='Update' id="updatefBtn"
                                data-foodkey="{{i.id}}"></td>
                        <td><input type='button' class='btn btn-danger btn-sm' value='Delete' id="deletefBtn"
                                data-foodkey="{{i.id}}"></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

templates/ordercrud.html
<script>
    $(document).ready(function(){

         //CreateData

         $('#createoBtn').click(function(){
            output = " ";
            console.log('hello')
            let order = $('#id_order').val()
            let ordered_by = $('#id_ordered_by').val()
            let status = $('#id_status').val()
            let csrfmiddlewaretoken = $(".order-container input[name='csrfmiddlewaretoken']").val()
            console.log(csrfmiddlewaretoken)
            if( order ==" " || ordered_by  ==" " || status ==""){
                     console.log("Fields cann't be empty")
            }else{
                fdata = {
                    'order': order,
                    'ordered_by': ordered_by,
                    'status':status,
                    'csrfmiddlewaretoken':csrfmiddlewaretoken
                },
                console.log('Data:',fdata);
                console.log("Sending Data...")
                $.ajax({
                    url: "{% url 'ordercreate' %}",
                    method: "POST",
                    data: fdata,
                    dataType: 'json',
                    success:function(response){
                            $('.order-messages').text("Form Submitted Sucessfully");
                            $('.order-messages').show()
                            x = response.order_queryset
                            console.log(x);
                            for(i=0; i < x.length; i++){
                               output +="<tr>"+
                                "<td>"+x[i].order_id+"</td>"+
                                "<td>"+x[i].ordered_by_id+"</td>"+
                                "<td>"+x[i].ordered_on+"</td>"+
                                "<td>"+x[i].status+"</td>"+
                                "<td><input type='button' class='btn btn-info btn-sm' value='Update' data-orderkey =" + x[i].id + ">" +
                                "<td><input type='button' class='btn btn-danger btn-sm' value='Delete' data-orderkey =" + x[i].id + ">" +
                                "</tr>"
                            }

                            $('.order-list tbody').html(output)
                            $('.order-container')[0].reset();

                    },
                    error: function(error){
                            console.log(error)
                    }
                })

            }
        })


    })
</script>

templates/ordercruddata.html
<script>
    $(document).ready(function () {

        //CreateData
        $('#createoBtn').click(function () {
            output = " ";
            console.log('hello')
            let order = $('#id_order').val()
            let ordered_by = $('#id_ordered_by').val()
            let status = $('#id_status').val()
            let csrfmiddlewaretoken = $(".order-container input[name='csrfmiddlewaretoken']").val()
            console.log(csrfmiddlewaretoken)
            if (order == " " || ordered_by == " " || status == "") {
                console.log("Fields cann't be empty")
            } else {
                fdata = {
                    'order': order,
                    'ordered_by': ordered_by,
                    'status': status,
                    'csrfmiddlewaretoken': csrfmiddlewaretoken
                },
                    console.log('Data:', fdata);
                console.log("Sending Data...")
                $.ajax({
                    url: "{% url 'ordercreate' %}",
                    method: "POST",
                    data: fdata,
                    dataType: 'json',
                    success: function (response) {
                        htmlp = "<div style='background-color: rgba(107, 255, 1, 0.92);text-align: center; padding:1rem; color: white;' role='alert'><strong>Order Created Sucessfully!</strong></div>"
                        $('.order-messages').html(htmlp);
                        $('.order-messages').show()
                        x = response.order_queryset
                        console.log(x);
                        for (i = 0; i < x.length; i++) {
                            output += "<tr>" +
                                "<td>" + x[i].order_id + "</td>" +
                                "<td>" + x[i].ordered_by_id + "</td>" +
                                "<td>" + x[i].ordered_on + "</td>" +
                                "<td>" + x[i].status + "</td>" +
                                "<td><input type='button' class='btn btn-info btn-sm' value='Update' data-orderkey =" + x[i].id + ">" +
                                "<td><input type='button' class='btn btn-danger btn-sm' value='Delete' data-orderkey =" + x[i].id + ">" +
                                "</tr>"
                        }

                        $('.order-list tbody').html(output)
                        $('.order-container')[0].reset();

                    },
                    error: function (error) {
                        console.log(error)
                    }
                })

            }
        })





    })
</script>

templates/photo.html
{% extends "base.html" %}
{% block body %}
<div class="mt-3">
    <div id="alert-box"></div>
    <div id="img-box"></div>

    <form id="p-form" autocomplete="off">
        <h5>Example 1</h5>
        <p>This is a simple ajax image preview in file upload with ajax submit</p>
        <hr>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Send</button>
    </form>

</div>
{% endblock body %}

templates/searchenginedata.html
<script>

    //Function Prototype    
    const sendSearchData = (keyword) => {
        $.ajax({
            type: "POST",
            url: "{% url 'search_engine' %}",
            data: {
                'csrfmiddlewaretoken': csrf_token,  //const csrf_token ==...
                'keyword': keyword,
            },
            success: function (response) {
                console.log(response)
                const data = response.data
                console.log('value:', searchinput.value.length)
                if (searchinput.value.length > 0) {
                    searchquery.classList.remove("not-visible");
                    searchquery.classList.add("visible");
                    if (Array.isArray(data)) {

                        searchquery.innerHTML = " "  //start with empty
                        data.forEach(keyword => {
                            searchquery.innerHTML +=
                                `<div><b>${keyword.name}</b></div> `
                        })
                    } else {
                        searchquery.innerHTML =
                            `<div><b>${data}</b></div> `
                    }
                } else {
                    searchquery.classList.remove("visible");
                    searchquery.classList.add("not-visible");
                }
            },
            error: function (error) {
                console.log(error.data)
            }
        })
    }


    const searchform = document.getElementById("search-form")
    const searchinput = document.getElementById("search-input")
    const searchquery = document.getElementById("search-query")

    const csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value
    console.log(csrf_token)
    searchinput.addEventListener("keyup", e => {
        console.log("printing", e.target.value)
        sendSearchData(e.target.value);
    })

</script>